### PR TITLE
testing: make TestConcurrentHandleRegion stable

### LINKED ISSUE #1861: TestConcurrentHandleRegion report POTENTIAL DEADLOCK
<details> <summary> CLICK SHOW DETAIL </summary>

```
[2019-10-29T06:26:42.744Z] POTENTIAL DEADLOCK:
[2019-10-29T06:26:42.744Z] Previous place where the lock was grabbed
[2019-10-29T06:26:42.744Z] goroutine 38756 lock 0xc0007940e0
[2019-10-29T06:26:42.744Z] cluster.go:438 server.(*RaftCluster).processRegionHeartbeat { c.Lock() } <<<<<
[2019-10-29T06:26:42.744Z] cluster_worker.go:31 server.(*RaftCluster).HandleRegionHeartbeat { if err := c.processRegionHeartbeat(region); err != nil { }
[2019-10-29T06:26:42.744Z] cluster_test.go:599 server.(*testClusterSuite).TestConcurrentHandleRegion.func2 { err := s.svr.cluster.HandleRegionHeartbeat(core.NewRegionInfo(region, region.Peers[0])) }
[2019-10-29T06:26:42.744Z] 
[2019-10-29T06:26:42.744Z] Have been trying to lock it again for more than 30s
[2019-10-29T06:26:42.744Z] goroutine 38425 lock 0xc0007940e0
[2019-10-29T06:26:42.744Z] cluster.go:438 server.(*RaftCluster).processRegionHeartbeat { c.Lock() } <<<<<
[2019-10-29T06:26:42.744Z] cluster_worker.go:31 server.(*RaftCluster).HandleRegionHeartbeat { if err := c.processRegionHeartbeat(region); err != nil { }
[2019-10-29T06:26:42.744Z] cluster_test.go:599 server.(*testClusterSuite).TestConcurrentHandleRegion.func2 { err := s.svr.cluster.HandleRegionHeartbeat(core.NewRegionInfo(region, region.Peers[0])) }
[2019-10-29T06:26:42.744Z] 
[2019-10-29T06:26:42.744Z] 
[2019-10-29T06:26:42.744Z] Here is what goroutine 38756 doing now
[2019-10-29T06:26:42.744Z] goroutine 38756 [semacquire]:
[2019-10-29T06:26:42.744Z] sync.runtime_SemacquireMutex(0xc00000e0a4, 0x3100000000)
[2019-10-29T06:26:42.744Z] 	/usr/local/go/src/runtime/sema.go:71 +0x3d
[2019-10-29T06:26:42.744Z] sync.(*Mutex).Lock(0xc00000e0a0)
[2019-10-29T06:26:42.744Z] 	/usr/local/go/src/sync/mutex.go:134 +0x149
[2019-10-29T06:26:42.744Z] github.com/sasha-s/go-deadlock.(*lockOrder).PreLock(0xc00000e0a0, 0x4, 0x195e9e0, 0xc000d1bb30)
[2019-10-29T06:26:42.744Z] 	/home/jenkins/agent/workspace/pd_test/go/pkg/mod/github.com/sasha-s/go-deadlock@v0.2.0/deadlock.go:251 +0xfa
[2019-10-29T06:26:42.744Z] github.com/sasha-s/go-deadlock.PreLock(...)
[2019-10-29T06:26:42.744Z] 	/home/jenkins/agent/workspace/pd_test/go/pkg/mod/github.com/sasha-s/go-deadlock@v0.2.0/deadlock.go:131
[2019-10-29T06:26:42.744Z] github.com/sasha-s/go-deadlock.lock(0xc000cad110, 0x195e9e0, 0xc000d1bb30)
[2019-10-29T06:26:42.744Z] 	/home/jenkins/agent/workspace/pd_test/go/pkg/mod/github.com/sasha-s/go-deadlock@v0.2.0/deadlock.go:147 +0xa4
[2019-10-29T06:26:42.744Z] github.com/sasha-s/go-deadlock.(*RWMutex).RLock(0xc000d1bb30)
[2019-10-29T06:26:42.744Z] 	/home/jenkins/agent/workspace/pd_test/go/pkg/mod/github.com/sasha-s/go-deadlock@v0.2.0/deadlock.go:110 +0xab
[2019-10-29T06:26:42.744Z] github.com/pingcap/pd/server/core.(*BasicCluster).GetStoreRegionCount(0xc000d1bb30, 0x4, 0x0)
[2019-10-29T06:26:42.744Z] 	/home/jenkins/agent/workspace/pd_test/go/src/github.com/pingcap/pd/server/core/basic_cluster.go:190 +0x5f
[2019-10-29T06:26:42.744Z] github.com/pingcap/pd/server.(*RaftCluster).updateStoreStatusLocked(0xc0007940e0, 0x4)
[2019-10-29T06:26:42.744Z] 	/home/jenkins/agent/workspace/pd_test/go/src/github.com/pingcap/pd/server/cluster.go:490 +0xb6
[2019-10-29T06:26:42.744Z] github.com/pingcap/pd/server.(*RaftCluster).processRegionHeartbeat(0xc0007940e0, 0xc002a251e0, 0x0, 0x0)
[2019-10-29T06:26:42.744Z] 	/home/jenkins/agent/workspace/pd_test/go/src/github.com/pingcap/pd/server/cluster.go:470 +0x10b3
[2019-10-29T06:26:42.744Z] github.com/pingcap/pd/server.(*RaftCluster).HandleRegionHeartbeat(0xc0007940e0, 0xc002a251e0, 0x0, 0x0)
[2019-10-29T06:26:42.744Z] 	/home/jenkins/agent/workspace/pd_test/go/src/github.com/pingcap/pd/server/cluster_worker.go:31 +0x79
[2019-10-29T06:26:42.744Z] github.com/pingcap/pd/server.(*testClusterSuite).TestConcurrentHandleRegion.func2(0xc000118cb0, 0xc000346ea0, 0xc002dfa300, 0xc0005ae2d0)
[2019-10-29T06:26:42.744Z] 	/home/jenkins/agent/workspace/pd_test/go/src/github.com/pingcap/pd/server/cluster_test.go:599 +0x125
[2019-10-29T06:26:42.744Z] created by github.com/pingcap/pd/server.(*testClusterSuite).TestConcurrentHandleRegion
[2019-10-29T06:26:42.745Z] 	/home/jenkins/agent/workspace/pd_test/go/src/github.com/pingcap/pd/server/cluster_test.go:597 +0x18aa
[2019-10-29T06:26:42.745Z] 
[2019-10-29T06:26:42.745Z] Other goroutines holding locks:
[2019-10-29T06:26:42.745Z] goroutine 16357 lock 0xc0002a2780
[2019-10-29T06:26:42.745Z] schedule/operator_controller.go:585 schedule.(*OperatorController).OperatorCount { oc.RLock() } <<<<<
[2019-10-29T06:26:42.745Z] schedule/checker_controller.go:59 schedule.(*CheckerController).CheckRegion { if opController.OperatorCount(operator.OpLeader) < c.cluster.GetLeaderScheduleLimit() && }
[2019-10-29T06:26:42.745Z] coordinator.go:119 server.(*coordinator).patrolRegions { checkerIsBusy, ops := c.checkers.CheckRegion(region) }
```

</details>

### PR DESCRIPTION
**Pull request by lhy1024**
Signed-off-by: lhy1024 <admin@liudos.us>

### What problem does this PR solve? 

fix #1861

### Check List 

Tests 

 - Unit test

### CODE REVIEW

**Comment by lhy1024** [comment]
@disksing @nolouch @Luffbee PTAL

**Comment by Luffbee** [comment]
So, the root of #1861 is there is too many goroutines?

**Comment by lhy1024** [comment]
@Luffbee the root should be too slow, but i have no idea to speed up it.

**Pull request merged**
