### PR TITLE
*: update etcd 

### PR DESCRIPTION
**Pull request by nolouch**
### What problem does this PR solve? 
- customized etcd logger
- fix prevote bug
- fast drop propose and read
- fix the issue about renew a lease with long TTL.
- Improve backend ( boltDB

### What is changed and how it works?
update etcd.

### Check List 

Tests 

 - Unit test
 - Integration test

### CODE REVIEW

**Comment by rleungx** [comment]
@nolouch This PR could be merged now?

**Comment by nolouch** [comment]
@rleungx  Yes, this PR already running 5 days in schordinger and no problem now, I think we can merge it.

**Pull request merged**
