### PR TITLE
Support querying a single parameter 

### PR DESCRIPTION
**Pull request by wq1019**
UCP: #2228

Signed-off-by: wq1019 <2013855675@qq.com>

### What problem does this PR solve? 
Support querying a single parameter for `component` subcommand in `pd-ctl`.
### What is changed and how it works?
Filtering the parameter list only returns a single parameter of the API result.
### Check List 

Tests 

 - Unit test

### CODE REVIEW

**Comment by wq1019** [comment]
@sre-bot /run-all-tests

**Comment by wq1019** [comment]
@rleungx I don't understand why `Travis CI` makes mistakes. Can you help me to have a look?

**Comment by wq1019** [comment]
> @rleungx I don't understand why `Travis CI` makes mistakes. Can you help me to have a look?

**Comment by rleungx** [comment]
@wq1019 Oh, sorry. I realized the component command will be removed in the next version. See #2349. But if you want, you can still implement it for config subcommand.

**Comment by wq1019** [comment]
> @wq1019 Oh, sorry. I realized the component command will be removed in the next version. See #2349. But if you want, you can still implement it for config subcommand.

Can the new command be like this:
```
>> config show 127.0.0.1:20160 paramName
```

**Comment by rleungx** [comment]
@wq1019 Would you like to pick another issue? It's my fault, I forgot to close that issue when I raise the PR. Also, you can join our [SIG](https://github.com/pingcap/community/tree/master/special-interest-groups/sig-scheduling) if you want.

**Pull request closed without merging**
