### PR TITLE
*: migrate to go1.11

### PR DESCRIPTION
**Pull request by disksing**
## What have you changed? (required)
Using go1.11

## What are the type of the changes (required)?
- Improvement (non-breaking change which is an improvement to an existing feature)\

## How has this PR been tested (required)?
make dev

### CODE REVIEW

**Comment by rleungx** [comment]
BTW, do we intend to use `vgo`?

**Comment by disksing** [comment]
@rleungx I think so. Hope it is better than dep, and glide, and godeps...

**Comment by siddontang** [comment]
Does TiDB support Go 1.11 now? @disksing

**Comment by siddontang** [comment]
maybe better to support 1.10 and 1.11

**Comment by disksing** [comment]
@siddontang They have PR to update to 1.11 too.
The `gofmt` tool shipped with go1.11 has different formatting rule compared to go1.10. So we can only support one of them in development. For compiling, 1.9+ should be ok.

**Pull request merged**
