### PR TITLE
*: support set leader priority to etcd members.

### PR DESCRIPTION
**Pull request by disksing**
Require https://github.com/pingcap/kvproto/pull/228 be merged first.

This PR allows administrator to assign leader priority for each pd member. We can do it using pd-ctl:
```
> member leader_priority $PD_NAME $PRIORITY
```
or HTTP API:
```
 curl -X POST -d '{"leader-priority": $PRIORITY}' http://127.0.0.1:2379/pd/api/v1/members/name/$PD_NAME
```

By default, a member's leader priority is 0. The priority can be set to a positive or negative number.

The PD with the maximum leader priority will become the etcd leader. In order to achieve this goal, each online PD server periodically compares its priority with leader's, propose a transfer leader command if it has a higher priority.

### CODE REVIEW

**Comment by siddontang** [comment]
no need to check PD leader itself?

**Comment by disksing** [comment]
I'm going to do it in a different PR. This one is already too complicated.

**Pull request merged**
