### PR TITLE
use kvproto/pkg/util package for message codec.

### PR DESCRIPTION
**Pull request by qiuyesuifeng**
@disksing @siddontang  PTAL

### CODE REVIEW

**Comment by disksing** [comment]
LGTM. But please fix CI failure before merge PR. It looks like you need to update Makefile to `go get` the new dependency.

**Comment by qiuyesuifeng** [comment]
@disksing  It depends on the PR in pingcap/kvproto, so the CI will be well after that be merged.

**Comment by qiuyesuifeng** [comment]
@siddontang PTAL

**Comment by siddontang** [comment]
LGTM

**Comment by ngaut** [comment]
LGTM

**Pull request merged**
