### PR TITLE
*: switch coverage test to Codecov 

### PR DESCRIPTION
**Pull request by rleungx**
### What problem does this PR solve? 
There are a lot of issues which are not resolved in `Coveralls`. Another coverage test `Codecov` is much better than it.

### What is changed and how it works?
The PR switches our coverage test from `Coveralls` to `Codecov`.

### Check List 

Tests 

 - No code

### CODE REVIEW

**Comment by siddontang** [comment]
But CI failed @rleungx

**Comment by rleungx** [comment]
@siddontang #1400 is trying to fix this problem. The error is not related to this PR.

**Pull request merged**
