### PR TITLE
Add native Windows build script

### PR DESCRIPTION
**Pull request by Hoverbear**
### What problem does this PR solve? 

Adds native Windows build script for developer usage.

It's possible to build `pd` in the WSL (Linux for Windows) but it's not possible to run it due to memmap differences that are known and reported. (https://github.com/etcd-io/bbolt/issues/144)

This script requires only Go, Git, and powershell to be available on the machine as far as I can tell. (I'm using a pretty basic windows machine)

Here's a demo running `pd` on native Windows powershell, `tikv` on wsl, and the `client-rust` on wsl as well: 
image

Here's the `--version` output:

image

We shouldn't announce/advertise this though because we haven't done any serious benchmarking or support testing. This is simply to enable Windows users to develop on pd/tikv without needing Docker.

### What is changed and how it works?

A `build.ps1` file was added since a minimal windows environment does not include `make` (`nmake` is available if you use the C++ dev tools but it's not fully compatible, we might try to use it and have errors later).

A Windows user using Powershell can invoke this with `./build` and will find familiar binaries at `bin/*`. They'll see from the script when they run it that these are created:

image

### Check List 

Tests 

 - No code

Code changes

Side effects

 - Increased code complexity

Related changes

 - Need to be included in the release notes

### CODE REVIEW

**Comment by nrc** [comment]
I don't think I can review this sorry, I don't know the powershell syntax, nor PD.

**Comment by Hoverbear** [comment]
Ok, sorry. :)

**Comment by Hoverbear** [comment]
@disksing I don't really understand how this PR is causing the CI to be red. Could you PTAL?

**Comment by disksing** [comment]
@Hoverbear Tests are not stable. Not your fault :)

**Comment by kennytm** [comment]
Interestingly the `pd-server.exe` can be executed directly inside WSL 1, so you don't need to launch PowerShell to run PD.

**Comment by Hoverbear** [comment]
Indeed! You can run it directly in wsl2 too. :) You could also launch it from CMD.

**Comment by kennytm** [comment]
I believe etcd-io/bbolt#144 is already fixed in WSL 2 so we could keep using the Linux version there 😅

**Comment by Hoverbear** [comment]
Sure!

**Pull request merged**
