### PR TITLE
use gzip_handler of  dashboard

### PR DESCRIPTION
**Pull request by niedhui**
### What problem does this PR solve? 

Add gzip support for dashboard uiserver.

### Check List 

Tests 

 - Manual test (add detailed scripts or steps below)

1. check the response content-encoding and size in the browser 
2. using `curl` test request resource with or without the `Accept-Encoding: gzip, deflate, br` header

related to https://github.com/pingcap-incubator/tidb-dashboard/pull/514

### CODE REVIEW

**Comment by breeswish** [comment]
I discovered that actually we have a 1-line solution: https://godoc.org/github.com/gorilla/handlers#CompressHandler would you like to have a try?

**Comment by niedhui** [comment]
If https://github.com/pingcap-incubator/tidb-dashboard/pull/521 is acceptable, I will update this to just use [httpgzip](https://github.com/shurcooL/httpgzip), and it avoids the unzip-then-zip issue

**Comment by breeswish** [comment]
@niedhui Cool!

**Comment by breeswish** [comment]
I released a new version of UI assets. You can update the dep of tidb-dashboard to latest commit (b8b98ac907d5429395c18d95b1bb03e524005503). This might resolve the CI failure.

**Comment by nolouch** [comment]
@breeswish @HunDunDM Can we merge this PR?

**Comment by breeswish** [comment]
@nolouch Yes

**Pull request merged**
