### PR TITLE
*: fix go mod tidy and clean up some dependencies

### LINKED ISSUE #1329: make failed after running go mod tidy
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
First run `GO111MODULE=on go mod tidy`, then `make`

2. What did you expect to see?
make successfully

3. What did you see instead?
```
CGO_ENABLED=0 go build -mod=vendor -ldflags '-X "github.com/pingcap/pd/server.PDReleaseVersion=v2.1.0-rc.2-45-g1c25147-dirty" -X "github.com/pingcap/pd/server.PDBuildTS=2018-11-14 09:35:42" -X "github.com/pingcap/pd/server.PDGitHash=1c25147f8ae58c4463f38af65f8873efb278752a" -X "github.com/pingcap/pd/server.PDGitBranch=master"' -o bin/pd-server cmd/pd-server/main.go
build golang.org/x/net/context: cannot find module for path golang.org/x/net/context
make: *** [build] Error 1
```

4. What version of PD are you using (`pd-server -V`)?
master

### PR DESCRIPTION
**Pull request by rleungx**
### What problem does this PR solve? 
The problem of #1329 is caused by our cleanup shell script. After we introduce go module, the original shell script will delete `vendor/modules.txt` which leads to #1329. 

> The `vendor/modules.txt` file, which describes how each entry in go.mod file corresponds to which subdirectory within vendor/

### What is changed and how it works?
This PR fixes the problem which we can not use `go mod tidy` and cleans up some unused dependencies. Closes #1329. 

### Check List 

Tests 

 - No code

### CODE REVIEW

**Comment by rleungx** [comment]
PTAL @disksing @nolouch

**Comment by gregwebs** [comment]
We will need this in other repos as well (tidb-operator and tidb come to mind).

**Comment by rleungx** [comment]
@gregwebs AFAIK, tidb does not use vendor for managing dependencies anymore. As for tidb-operator, it doesn't have this script.

**Pull request merged**
