### PR TITLE
*: some fixes for release 3.0

### PR DESCRIPTION
**Pull request by rleungx**
### What problem does this PR solve? 
cherry-pick
- [x] #1617 
- [x] #1616 
- [x] #1613 
- [x] #1609 

### Check List 

Tests 

 - Unit test
 - Integration test

Related changes

 - Need to be included in the release notes

### CODE REVIEW

**Comment by rleungx** [comment]
/run-all-tests tidb=release-3.0 tikv=release-3.0 tidb-test=release-3.0

**Comment by nolouch** [comment]
/run-all-tests tidb=release-2.1 tikv=release-2.1 tidb-test=release-2.1

**Comment by rleungx** [comment]
/run-all-tests tidb=release-3.0 tikv=release-3.0 tidb-test=release-3.0

**Pull request merged**
