### PR TITLE
make operatorStepDuration metric thread-safe

### PR DESCRIPTION
**Pull request by wangrzneu**
### What problem does this PR solve?

Close https://github.com/pingcap/pd/issues/1665

### What is changed and how it works?
- get operator start time from OpStatusTracker directly
- record and observe the finish time of each operator step excatly once using CAS (Compare And Swap)
### Check List
Tests
- Unit test

### Release note
No release note

### CODE REVIEW

**Comment by rleungx** [comment]
Is it ready to review?

**Comment by wangrzneu** [comment]
@nolouch PTAL

**Pull request merged**
