### PR TITLE
Bump to v2.1.7

### PR DESCRIPTION
**Pull request by overvenus**
Bump to v2.1.7

### CODE REVIEW

**Comment by disksing** [comment]
/run-all-tests tidb=release-2.1 tikv=release-2.1 tidb-test=release-2.1

**Comment by zhouqiang-cl** [comment]
/run-all-tests tidb=release-2.1 tikv=release-2.1 tidb-test=release-2.1

**Comment by disksing** [comment]
tidb-test problem, merging.

**Pull request merged**
