### PR TITLE
[WIP/DNM]Structured log

### LINKED ISSUE #459: pd.toml lacks [server] section
For that tikv uses [server] section.

### PR DESCRIPTION
**Pull request by andelf**
* use logrus to replace ngaut/log
* isolate config as subpackage
* isolate ServerConfig, fix #459 
* [ ] structured log with region info
* [ ] backward compatibility
* [ ] additional log #586

### CODE REVIEW

**Comment by siddontang** [comment]
Please split your PR, we can replace ngaut/log with logrus at first.

**Comment by andelf** [comment]
@siddontang this is the SPLIT.

**Comment by siddontang** [comment]
No, you can

1. Remove ngaut/log, use logrus with previous format. 
2. Update config
3. Use our format

**Comment by andelf** [comment]
Should config / logutil be a subpackage?

**Comment by siddontang** [comment]
yes, we can use a subpackage later.

**Comment by overvenus** [comment]
Server highly depends on Config, I think we'd better not separate it from Server. 
What's your opinion? @siddontang @disksing @nolouch

**Comment by siddontang** [comment]
Any update, @andelf ?

**Comment by andelf** [comment]
Closed, and discarded by #610

**Pull request closed without merging**
