### PR TITLE
pdctl: should not use a format string

### PR DESCRIPTION
**Pull request by shafreeck**
Signed-off-by: Shafreeck Sea <shafreeck@gmail.com>

### What problem does this PR solve? 

There is a bug when constructs an URL string when does `remove-tombstone`

```
Failed to remove tombstone store parse http://pd-test-pd:2379/pd/api/v1/stores/remove-tombstone%!(EXTRA string=): invalid URL escape "%!("
```

### What is changed and how it works?

Remove the unexpected `fmt.Sprintf`

### Check List 

Tests 

 - Unit test

### CODE REVIEW

**Comment by Luffbee** [comment]
These `Sprintf` with non-literal format string looks dangerous. Maybe use a function to construct these strings is a better way to solve the root problem?

**Comment by disksing** [comment]
So no unit test covers it?

**Comment by shafreeck** [comment]
@disksing Good catch. I am afraid not.

**Comment by shafreeck** [comment]
@Luffbee I don't get your point too much. Why does `Sprintf` look dangerous?

**Comment by Luffbee** [comment]
> @Luffbee I don't get your point too much. Why does `Sprintf` look dangerous?

There is no check for the format string and arguments during compile time in go. So, with non-literal format string, it's easy to write bugs like this one, and it's hard to discover this kind of bugs.

**Comment by shafreeck** [comment]
@Luffbee Good point. But I think this PR can be merged first. Maybe it's a little long term plan to reduce format output.

**Comment by nolouch** [comment]
Why your previous test not work? I remember there is a test in `tests/pdctl`.

**Comment by shafreeck** [comment]
Anyway, I think this PR could be merged first. We can create issues for other problems.

**Pull request merged**
