### PR TITLE
server/coordinator: fix some tests

### PR DESCRIPTION
**Pull request by huachaohuang**
We need to separate the balance tests and replica tests so that they will not
screw up each other occasionally.

### CODE REVIEW

**Comment by siddontang** [comment]
CI failed

**Comment by siddontang** [comment]
Too many other changes, should clear it first.

**Comment by huachaohuang** [comment]
Oh, I forgot to change the base branch, PTAL again.

**Comment by siddontang** [comment]
PTAL @overvenus

**Pull request merged**
