### PR TITLE
abandon vendor

### PR DESCRIPTION
**Pull request by disksing**
Signed-off-by: disksing <i@disksing.com>

### What problem does this PR solve? 
Remove vendor directory. Make code base clean.

NOTE: go modules are not well supported by some IDEs. You can manually run `go mod vendor` to make your editor work. The `vendor` directory is already added to `.gitignore`.

### What is changed and how it works?
- remove /vendor
- update makefile

### Check List 

Tests 
 - Unit test

Side effects
 - Breaking backward compatibility: does not support old version go (earlier than 1.11) anymore

### CODE REVIEW

**Comment by gregwebs** [comment]
This change is good in principle: the problems are just of adapting workflows. IDE is a good one to point out. The main thing that comes to my mind would be CI or any docker builds. Will the CI go from one quick clone to 50 separate clones now, or will we be able to cached the go modules across builds?

**Comment by disksing** [comment]
@gregwebs Good point. I'll check if there are any cache options we can use in CI environments.

**Comment by disksing** [comment]
@gregwebs Done for Circle and Travis. Our internal CI doesn't support build cache yet. Sadly.

**Comment by gregwebs** [comment]
LGTM then. But internal CI might be a reason not to make this change yet. I think due to tidb doing this and the build slowing down there may be some effort to figure out dependency caching.

**Pull request merged**
