### PR TITLE
*: cherry pick some fixes to release 2.1

### PR DESCRIPTION
**Pull request by nolouch**
### What problem does this PR solve? 
some fixes to release 2.1

### What is changed and how it works?
cherry pick

### Check List 

Tests 

 - Unit test

### CODE REVIEW

**Comment by nolouch** [comment]
/run-all-tests tidb=release-2.1 tikv=release-2.1 tidb-test=release-2.1

**Comment by nolouch** [comment]
/run-all-tests tidb=release-2.1 tikv=release-2.1 tidb-test=release-2.1

**Comment by nolouch** [comment]
/run-all-tests tidb=release-2.1 tikv=release-2.1 tidb-test=release-2.1

**Comment by zhouqiang-cl** [comment]
/run-all-tests tidb=release-2.1 tikv=release-2.1 tidb-test=release-2.1

**Comment by zhouqiang-cl** [comment]
/run-all-tests tidb=release-2.1 tikv=release-2.1 tidb-test=release-2.1

**Pull request merged**
