### PR TITLE
Release 2.0.4

### PR DESCRIPTION
**Pull request by disksing**

### CODE REVIEW

**Comment by disksing** [comment]
/run-all-tests tidb=release-2.0 tikv=release-2.0 tidb-test=release-2.0

**Comment by siddontang** [comment]
LGTM

**Comment by siddontang** [comment]
CI failed @disksing

**Comment by disksing** [comment]
/run-all-tests tidb=release-2.0 tikv=release-2.0 tidb-test=release-2.0

**Pull request merged**
