### PR TITLE
server: GetAllStores should not return tombstone stores

### PR DESCRIPTION
**Pull request by huachaohuang**
### What problem does this PR solve? 

`GetAllStores` should not return tombstone stores in most cases. We can
add an option to support that if we needs it later.

### What is changed and how it works?

`GetAllStores` filters out tombstone stores.

### Check List 

Tests 

 - Unit test

### CODE REVIEW

**Comment by overvenus** [comment]
Looks like a breaking changes, what if we do want get tombstone stores?

**Comment by huachaohuang** [comment]
@overvenus we can add an option in the request when we need that later, but I don't see that requirement for now.

**Comment by rleungx** [comment]
@huachaohuang How about adding an optional parameter to filter the tombstone stores so that it won't be a breaking change?

**Comment by huachaohuang** [comment]
https://github.com/pingcap/kvproto/pull/359
@rleungx @disksing @nolouch PTAL

**Comment by huachaohuang** [comment]
@overvenus I think there is no compatibility problem now.

**Comment by huachaohuang** [comment]
@rleungx @disksing PTAL

**Pull request merged**
