### PR TITLE
cherry-pick commits to release-2.0

### PR DESCRIPTION
**Pull request by nolouch**

### CODE REVIEW

**Comment by disksing** [comment]
@nolouch We only need to cherry-pick bug fixes. Improvements will be released in v2.1.

**Comment by nolouch** [comment]
/run-all-tests tidb=release-2.0 tikv=release-2.0 tidb-test=release-2.0

**Comment by disksing** [comment]
PTAL @siddontang @Connor1996

**Comment by siddontang** [comment]
LGTM

**Pull request merged**
