### PR TITLE
pd-ctl: add policy selection for split region

### PR DESCRIPTION
**Pull request by Connor1996**
## What have you changed? (required)
Currently TiKV support get approximate middle key from properties, so when split region add a check-policy field to specify to use which way.

## What are the type of the changes (required)?
Improvement (non-breaking change which is an improvement to an existing feature)

## How has this PR been tested (required)?
manual test

## Does this PR affect documentation (docs/docs-cn) update? (optional)
https://github.com/pingcap/docs-cn/pull/809

## Refer to a related PR or issue link (optional)
https://github.com/pingcap/kvproto/pull/287

### CODE REVIEW

**Comment by disksing** [comment]
Do we need to supply to split key to split region too?

**Comment by Connor1996** [comment]
@disksing No, there is a command for tikv-ctl to split region on specified split key. And this split region command for pd is just half split.

**Comment by disksing** [comment]
LGTM

**Comment by disksing** [comment]
Please switch to master kvproto before merge.

**Pull request merged**
