### PR TITLE
Reuse tsoresp

### PR DESCRIPTION
**Pull request by bradyjoestar**
### What problem does this PR solve? 
#1483 

### What is changed and how it works?
reuse tsoresp in tsoserver

### Check List 

Tests 

 - Integration test pd-tso-bench passed

### CODE REVIEW

**Comment by nolouch** [comment]
@bradyjoestar  Thanks! Could you show some benchmark?

**Comment by bradyjoestar** [comment]
`pd-tso-bench -interval 5s -C 1` optimized 
```
count:46571, max:1, min:0, >1ms:4, >2ms:0, >5ms:0, >10ms:0, >30ms:0
count:45611, max:2, min:0, >1ms:5, >2ms:1, >5ms:0, >10ms:0, >30ms:0
count:45669, max:2, min:0, >1ms:5, >2ms:1, >5ms:0, >10ms:0, >30ms:0
count:45838, max:1, min:0, >1ms:5, >2ms:0, >5ms:0, >10ms:0, >30ms:0
count:45655, max:2, min:0, >1ms:6, >2ms:1, >5ms:0, >10ms:0, >30ms:0
count:45603, max:1, min:0, >1ms:4, >2ms:0, >5ms:0, >10ms:0, >30ms:0
count:45555, max:2, min:0, >1ms:2, >2ms:2, >5ms:0, >10ms:0, >30ms:0
count:45716, max:2, min:0, >1ms:4, >2ms:2, >5ms:0, >10ms:0, >30ms:0
count:45624, max:1, min:0, >1ms:6, >2ms:0, >5ms:0, >10ms:0, >30ms:0
count:45807, max:2, min:0, >1ms:7, >2ms:1, >5ms:0, >10ms:0, >30ms:0
count:45543, max:2, min:0, >1ms:6, >2ms:2, >5ms:0, >10ms:0, >30ms:0
count:45564, max:1, min:0, >1ms:4, >2ms:0, >5ms:0, >10ms:0, >30ms:0
count:45703, max:2, min:0, >1ms:4, >2ms:2, >5ms:0, >10ms:0, >30ms:0
count:45746, max:1, min:0, >1ms:9, >2ms:0, >5ms:0, >10ms:0, >30ms:0
count:45574, max:2, min:0, >1ms:3, >2ms:2, >5ms:0, >10ms:0, >30ms:0
count:45529, max:2, min:0, >1ms:7, >2ms:1, >5ms:0, >10ms:0, >30ms:0
count:45697, max:1, min:0, >1ms:5, >2ms:0, >5ms:0, >10ms:0, >30ms:0
```

`pd-tso-bench -interval 5s -C 1` optimized before
```
count:46203, max:1, min:0, >1ms:3, >2ms:0, >5ms:0, >10ms:0, >30ms:0
count:45508, max:1, min:0, >1ms:3, >2ms:0, >5ms:0, >10ms:0, >30ms:0
count:45440, max:1, min:0, >1ms:7, >2ms:0, >5ms:0, >10ms:0, >30ms:0
count:45519, max:2, min:0, >1ms:6, >2ms:1, >5ms:0, >10ms:0, >30ms:0
count:45427, max:2, min:0, >1ms:3, >2ms:2, >5ms:0, >10ms:0, >30ms:0
count:45515, max:2, min:0, >1ms:3, >2ms:1, >5ms:0, >10ms:0, >30ms:0
count:45333, max:2, min:0, >1ms:5, >2ms:1, >5ms:0, >10ms:0, >30ms:0
count:45301, max:2, min:0, >1ms:3, >2ms:2, >5ms:0, >10ms:0, >30ms:0
count:45298, max:2, min:0, >1ms:6, >2ms:1, >5ms:0, >10ms:0, >30ms:0
count:45463, max:2, min:0, >1ms:4, >2ms:1, >5ms:0, >10ms:0, >30ms:0
count:45675, max:2, min:0, >1ms:2, >2ms:2, >5ms:0, >10ms:0, >30ms:0
count:45546, max:2, min:0, >1ms:4, >2ms:1, >5ms:0, >10ms:0, >30ms:0
count:45290, max:3, min:0, >1ms:2, >2ms:3, >5ms:0, >10ms:0, >30ms:0
count:45358, max:2, min:0, >1ms:5, >2ms:1, >5ms:0, >10ms:0, >30ms:0
count:45457, max:2, min:0, >1ms:7, >2ms:1, >5ms:0, >10ms:0, >30ms:0
count:45579, max:1, min:0, >1ms:7, >2ms:0, >5ms:0, >10ms:0, >30ms:0
count:45309, max:2, min:0, >1ms:4, >2ms:3, >5ms:0, >10ms:0, >30ms:0
count:45624, max:2, min:0, >1ms:6, >2ms:2, >5ms:0, >10ms:0, >30ms:0
count:45432, max:2, min:0, >1ms:3, >2ms:2, >5ms:0, >10ms:0, >30ms:0
count:45285, max:2, min:0, >1ms:3, >2ms:4, >5ms:0, >10ms:0, >30ms:0
count:45367, max:2, min:0, >1ms:6, >2ms:1, >5ms:0, >10ms:0, >30ms:0
```

**Comment by bradyjoestar** [comment]
```pd-tso-bench``` optimized after
```
count:1143109, max:5, min:0, >1ms:123482, >2ms:1978, >5ms:40, >10ms:0, >30ms:0
count:1164478, max:3, min:0, >1ms:109392, >2ms:411, >5ms:0, >10ms:0, >30ms:0
count:1150873, max:4, min:0, >1ms:130405, >2ms:1431, >5ms:0, >10ms:0, >30ms:0
count:1068498, max:4, min:0, >1ms:245276, >2ms:1556, >5ms:0, >10ms:0, >30ms:0
count:1076037, max:3, min:0, >1ms:228571, >2ms:1292, >5ms:0, >10ms:0, >30ms:0
count:1077425, max:5, min:0, >1ms:233556, >2ms:1185, >5ms:1, >10ms:0, >30ms:0
count:1079259, max:5, min:0, >1ms:217886, >2ms:1713, >5ms:233, >10ms:0, >30ms:0
count:1075914, max:6, min:0, >1ms:241988, >2ms:519, >5ms:2, >10ms:0, >30ms:0
count:1083190, max:5, min:0, >1ms:223754, >2ms:65, >5ms:1, >10ms:0, >30ms:0
count:1073176, max:4, min:0, >1ms:231879, >2ms:961, >5ms:0, >10ms:0, >30ms:0
count:1065293, max:4, min:0, >1ms:258250, >2ms:951, >5ms:0, >10ms:0, >30ms:0
count:1099162, max:5, min:0, >1ms:198545, >2ms:892, >5ms:1, >10ms:0, >30ms:0
count:1069539, max:5, min:0, >1ms:235035, >2ms:1371, >5ms:1, >10ms:0, >30ms:0
count:1080250, max:3, min:0, >1ms:228192, >2ms:2340, >5ms:0, >10ms:0, >30ms:0
count:1073297, max:4, min:0, >1ms:235794, >2ms:2078, >5ms:0, >10ms:0, >30ms:0
count:1064567, max:3, min:0, >1ms:252684, >2ms:214, >5ms:0, >10ms:0, >30ms:0
count:1087177, max:6, min:0, >1ms:226439, >2ms:809, >5ms:1, >10ms:0, >30ms:0
count:1085823, max:5, min:0, >1ms:222556, >2ms:1671, >5ms:1, >10ms:0, >30ms:0
count:1079338, max:3, min:0, >1ms:230566, >2ms:890, >5ms:0, >10ms:0, >30ms:0
count:1076724, max:5, min:0, >1ms:236459, >2ms:553, >5ms:1, >10ms:0, >30ms:0
count:1085891, max:4, min:0, >1ms:213284, >2ms:816, >5ms:0, >10ms:0, >30ms:0
count:1092555, max:3, min:0, >1ms:211022, >2ms:1966, >5ms:0, >10ms:0, >30ms:0
count:1078640, max:4, min:0, >1ms:241903, >2ms:68, >5ms:0, >10ms:0, >30ms:0
count:1077637, max:5, min:0, >1ms:227302, >2ms:785, >5ms:1, >10ms:0, >30ms:0
count:1082960, max:4, min:0, >1ms:222461, >2ms:800, >5ms:0, >10ms:0, >30ms:0
count:1089833, max:4, min:0, >1ms:213796, >2ms:1468, >5ms:0, >10ms:0, >30ms:0
count:1083417, max:4, min:0, >1ms:223021, >2ms:1304, >5ms:0, >10ms:0, >30ms:0
count:1098026, max:4, min:0, >1ms:190516, >2ms:1794, >5ms:0, >10ms:0, >30ms:0
count:1082734, max:3, min:0, >1ms:226777, >2ms:989, >5ms:0, >10ms:0, >30ms:0
count:1098012, max:5, min:0, >1ms:200704, >2ms:1538, >5ms:1, >10ms:0, >30ms:0
count:1081101, max:4, min:0, >1ms:218367, >2ms:1171, >5ms:0, >10ms:0, >30ms:0
count:1086549, max:3, min:0, >1ms:215312, >2ms:2175, >5ms:0, >10ms:0, >30ms:0
count:1075430, max:4, min:0, >1ms:244570, >2ms:765, >5ms:0, >10ms:0, >30ms:0
count:1069832, max:5, min:0, >1ms:253055, >2ms:187, >5ms:1, >10ms:0, >30ms:0
count:1080440, max:5, min:0, >1ms:235003, >2ms:622, >5ms:1, >10ms:0, >30ms:0
count:1079966, max:5, min:0, >1ms:231036, >2ms:661, >5ms:1, >10ms:0, >30ms:0
count:1084592, max:4, min:0, >1ms:215754, >2ms:1418, >5ms:0, >10ms:0, >30ms:0
count:1078856, max:3, min:0, >1ms:225506, >2ms:721, >5ms:0, >10ms:0, >30ms:0
count:1073306, max:3, min:0, >1ms:248501, >2ms:534, >5ms:0, >10ms:0, >30ms:0
count:1101161, max:3, min:0, >1ms:203926, >2ms:517, >5ms:0, >10ms:0, >30ms:0
count:1079504, max:5, min:0, >1ms:230711, >2ms:1204, >5ms:1, >10ms:0, >30ms:0
count:1075411, max:4, min:0, >1ms:239671, >2ms:1969, >5ms:0, >10ms:0, >30ms:0
count:1066721, max:5, min:0, >1ms:246281, >2ms:619, >5ms:1, >10ms:0, >30ms:0
count:1064617, max:5, min:0, >1ms:238391, >2ms:2133, >5ms:1, >10ms:0, >30ms:0
count:1092409, max:4, min:0, >1ms:209436, >2ms:578, >5ms:0, >10ms:0, >30ms:0
count:1088291, max:4, min:0, >1ms:217779, >2ms:556, >5ms:0, >10ms:0, >30ms:0
count:1083839, max:4, min:0, >1ms:223095, >2ms:858, >5ms:0, >10ms:0, >30ms:0
count:1078148, max:6, min:0, >1ms:234265, >2ms:566, >5ms:1, >10ms:0, >30ms:0
count:1079399, max:3, min:0, >1ms:223937, >2ms:1803, >5ms:0, >10ms:0, >30ms:0
count:1079202, max:3, min:0, >1ms:233735, >2ms:561, >5ms:0, >10ms:0, >30ms:0
count:1090578, max:4, min:0, >1ms:208384, >2ms:705, >5ms:0, >10ms:0, >30ms:0
count:1087698, max:4, min:0, >1ms:215440, >2ms:1331, >5ms:0, >10ms:0, >30ms:0
count:1082725, max:4, min:0, >1ms:228404, >2ms:602, >5ms:0, >10ms:0, >30ms:0
count:1087890, max:4, min:0, >1ms:228641, >2ms:661, >5ms:0, >10ms:0, >30ms:0
```

**Comment by bradyjoestar** [comment]
```pd-tso-bench``` optimze before
```
count:1143109, max:5, min:0, >1ms:123482, >2ms:1978, >5ms:40, >10ms:0, >30ms:0
count:1164478, max:3, min:0, >1ms:109392, >2ms:411, >5ms:0, >10ms:0, >30ms:0
count:1150873, max:4, min:0, >1ms:130405, >2ms:1431, >5ms:0, >10ms:0, >30ms:0
count:1068498, max:4, min:0, >1ms:245276, >2ms:1556, >5ms:0, >10ms:0, >30ms:0
count:1076037, max:3, min:0, >1ms:228571, >2ms:1292, >5ms:0, >10ms:0, >30ms:0
count:1077425, max:5, min:0, >1ms:233556, >2ms:1185, >5ms:1, >10ms:0, >30ms:0
count:1079259, max:5, min:0, >1ms:217886, >2ms:1713, >5ms:233, >10ms:0, >30ms:0
count:1075914, max:6, min:0, >1ms:241988, >2ms:519, >5ms:2, >10ms:0, >30ms:0
count:1083190, max:5, min:0, >1ms:223754, >2ms:65, >5ms:1, >10ms:0, >30ms:0
count:1073176, max:4, min:0, >1ms:231879, >2ms:961, >5ms:0, >10ms:0, >30ms:0
count:1065293, max:4, min:0, >1ms:258250, >2ms:951, >5ms:0, >10ms:0, >30ms:0
count:1099162, max:5, min:0, >1ms:198545, >2ms:892, >5ms:1, >10ms:0, >30ms:0
count:1069539, max:5, min:0, >1ms:235035, >2ms:1371, >5ms:1, >10ms:0, >30ms:0
count:1080250, max:3, min:0, >1ms:228192, >2ms:2340, >5ms:0, >10ms:0, >30ms:0
count:1073297, max:4, min:0, >1ms:235794, >2ms:2078, >5ms:0, >10ms:0, >30ms:0
count:1064567, max:3, min:0, >1ms:252684, >2ms:214, >5ms:0, >10ms:0, >30ms:0
count:1087177, max:6, min:0, >1ms:226439, >2ms:809, >5ms:1, >10ms:0, >30ms:0
count:1085823, max:5, min:0, >1ms:222556, >2ms:1671, >5ms:1, >10ms:0, >30ms:0
count:1079338, max:3, min:0, >1ms:230566, >2ms:890, >5ms:0, >10ms:0, >30ms:0
count:1076724, max:5, min:0, >1ms:236459, >2ms:553, >5ms:1, >10ms:0, >30ms:0
count:1085891, max:4, min:0, >1ms:213284, >2ms:816, >5ms:0, >10ms:0, >30ms:0
count:1092555, max:3, min:0, >1ms:211022, >2ms:1966, >5ms:0, >10ms:0, >30ms:0
count:1078640, max:4, min:0, >1ms:241903, >2ms:68, >5ms:0, >10ms:0, >30ms:0
count:1077637, max:5, min:0, >1ms:227302, >2ms:785, >5ms:1, >10ms:0, >30ms:0
count:1082960, max:4, min:0, >1ms:222461, >2ms:800, >5ms:0, >10ms:0, >30ms:0
count:1089833, max:4, min:0, >1ms:213796, >2ms:1468, >5ms:0, >10ms:0, >30ms:0
count:1083417, max:4, min:0, >1ms:223021, >2ms:1304, >5ms:0, >10ms:0, >30ms:0
count:1098026, max:4, min:0, >1ms:190516, >2ms:1794, >5ms:0, >10ms:0, >30ms:0
count:1082734, max:3, min:0, >1ms:226777, >2ms:989, >5ms:0, >10ms:0, >30ms:0
count:1098012, max:5, min:0, >1ms:200704, >2ms:1538, >5ms:1, >10ms:0, >30ms:0
count:1081101, max:4, min:0, >1ms:218367, >2ms:1171, >5ms:0, >10ms:0, >30ms:0
count:1086549, max:3, min:0, >1ms:215312, >2ms:2175, >5ms:0, >10ms:0, >30ms:0
count:1075430, max:4, min:0, >1ms:244570, >2ms:765, >5ms:0, >10ms:0, >30ms:0
count:1069832, max:5, min:0, >1ms:253055, >2ms:187, >5ms:1, >10ms:0, >30ms:0
count:1080440, max:5, min:0, >1ms:235003, >2ms:622, >5ms:1, >10ms:0, >30ms:0
count:1079966, max:5, min:0, >1ms:231036, >2ms:661, >5ms:1, >10ms:0, >30ms:0
count:1084592, max:4, min:0, >1ms:215754, >2ms:1418, >5ms:0, >10ms:0, >30ms:0
count:1078856, max:3, min:0, >1ms:225506, >2ms:721, >5ms:0, >10ms:0, >30ms:0
count:1073306, max:3, min:0, >1ms:248501, >2ms:534, >5ms:0, >10ms:0, >30ms:0
count:1101161, max:3, min:0, >1ms:203926, >2ms:517, >5ms:0, >10ms:0, >30ms:0
count:1079504, max:5, min:0, >1ms:230711, >2ms:1204, >5ms:1, >10ms:0, >30ms:0
count:1075411, max:4, min:0, >1ms:239671, >2ms:1969, >5ms:0, >10ms:0, >30ms:0
count:1066721, max:5, min:0, >1ms:246281, >2ms:619, >5ms:1, >10ms:0, >30ms:0
count:1064617, max:5, min:0, >1ms:238391, >2ms:2133, >5ms:1, >10ms:0, >30ms:0
count:1092409, max:4, min:0, >1ms:209436, >2ms:578, >5ms:0, >10ms:0, >30ms:0
count:1088291, max:4, min:0, >1ms:217779, >2ms:556, >5ms:0, >10ms:0, >30ms:0
count:1083839, max:4, min:0, >1ms:223095, >2ms:858, >5ms:0, >10ms:0, >30ms:0
count:1078148, max:6, min:0, >1ms:234265, >2ms:566, >5ms:1, >10ms:0, >30ms:0
count:1079399, max:3, min:0, >1ms:223937, >2ms:1803, >5ms:0, >10ms:0, >30ms:0
count:1079202, max:3, min:0, >1ms:233735, >2ms:561, >5ms:0, >10ms:0, >30ms:0
count:1090578, max:4, min:0, >1ms:208384, >2ms:705, >5ms:0, >10ms:0, >30ms:0
count:1087698, max:4, min:0, >1ms:215440, >2ms:1331, >5ms:0, >10ms:0, >30ms:0
count:1082725, max:4, min:0, >1ms:228404, >2ms:602, >5ms:0, >10ms:0, >30ms:0
count:1087890, max:4, min:0, >1ms:228641, >2ms:661, >5ms:0, >10ms:0, >30ms:0
```

**Comment by disksing** [comment]
According to my observation, there is no significant performance improvement? It is recommended not to do "smart optimization" as much as possible.

**Comment by nolouch** [comment]
Hi, @bradyjoestar, There is no promises that `gRPC` will no re-use the request in some time after `Send()`, so pass the point is dangerous. and there is no significant performance improvement, can we close it?

**Comment by bradyjoestar** [comment]
@nolouch 
It's a good question that how grpc handle the obsolete request. I have missed it.

Closed. 🍻

**Pull request closed without merging**
