### PR TITLE
balance: prevent access nil store when recovering cluster

### PR DESCRIPTION
**Pull request by nolouch**
we may access nil store when recovering cluster. this PR fix it.
PTAL @disksing @siddontang

### CODE REVIEW

**Comment by disksing** [comment]
With this fix, if a store never start after recover, then the replica will never be sufficient?

**Comment by siddontang** [comment]
mean that we may panic before?

**Comment by nolouch** [comment]
@disksing now recover just work for lost the PD data, all TiKV must restart after recovering the PD.
@siddontang  yep

**Comment by disksing** [comment]
LGTM.

**Comment by siddontang** [comment]
any test ?

**Comment by siddontang** [comment]
PTAL @disksing

**Comment by disksing** [comment]
LGTM

**Pull request merged**
