### PR TITLE
api: fix unexpected error when set config to the same value

### PR DESCRIPTION
**Pull request by disksing**
Signed-off-by: disksing <i@disksing.com>

### What problem does this PR solve? 
Fix part of https://github.com/pingcap/pd/issues/1899

### What is changed and how it works?
Check if the config item exists in any configuration.

### Check List 

Tests 
 - Unit test
 - Manual test

### CODE REVIEW

**Comment by rleungx** [comment]
It seems `config set location-labels ""` still cannot work.

**Comment by disksing** [comment]
@rleungx That's a different problem :(
Changed description to "fix part of #1899"

**Comment by shafreeck** [comment]
Is the flag `updated`, `found` necessary here?

I prefer to update the configuration in a simpler way:
1. Get the original config object `conf`
2. Unmarshal the data to conf. This will merge the old and new values
3. Return an error if there is, overwise, return OK

**Comment by disksing** [comment]
@shafreeck If client sends a wrong config, we will not know.

**Pull request merged**
