### PR TITLE
support leader check.

### PR DESCRIPTION
**Pull request by siddontang**
@ngaut

### CODE REVIEW

**Comment by ngaut** [comment]
We may return not_leader error then close connection.

**Comment by siddontang** [comment]
no need, if connection closed, client will ask etcd for new leader address again. 

Btw, the connection flow is request -> response, so only connection sending request can handle not leader error, other idles can't do it until sending a new request.

**Comment by ngaut** [comment]
It's a bad style to simply close connection. Because the client doesn't know why exactly.

**Comment by ngaut** [comment]
LGTM

**Pull request merged**
