### PR TITLE
Cherry-pick scatter range scheduler

### PR DESCRIPTION
**Pull request by nolouch**
cherry-pick scatter range scheduler.

### CODE REVIEW

**Comment by nolouch** [comment]
/run-all-tests tidb=release-2.0 tikv=release-2.0 tidb-test=release-2.0

**Comment by nolouch** [comment]
/run-all-tests tidb=release-2.0 tikv=release-2.0 tidb-test=release-2.0

**Comment by huachaohuang** [comment]
LGTM

**Pull request merged**
