### PR TITLE
update go.mod for tidb-dashboard

### PR DESCRIPTION
**Pull request by crazycs520**
Signed-off-by: crazycs520 <crazycs520@gmail.com>

### What problem does this PR solve? 

Update tidb-dashboard to 05-18, for PR https://github.com/pingcap-incubator/tidb-dashboard/pull/502

### Check List 

Tests 

 - No code

Side effects

 - No

Related changes

- Need to cherry-pick to the release branch

### Release note 

- Fix panic when generated SQL diagnosis report in dashboard.

### CODE REVIEW

**Comment by crazycs520** [comment]
@HunDunDM @breeswish PTAL

**Comment by HunDunDM** [comment]
need cherry-pick?

**Pull request merged**
