### PR TITLE
 Cherry-pick commits to release-2.0

### PR DESCRIPTION
**Pull request by nolouch**

### CODE REVIEW

**Comment by disksing** [comment]
There are commits that don't need to be merged to release-2.0 branch. You can cherry-pick the commits that are tagged with 'backport/release-2.0' label.

**Comment by nolouch** [comment]
done.PTAL

**Comment by disksing** [comment]
I think #1012 should be excluded too.

**Comment by nolouch** [comment]
@disksing  already done.

**Pull request merged**
