### PR TITLE
*: add etcd vendor

### PR DESCRIPTION
**Pull request by siddontang**
Embed etcd will introduce a huge vendor, so I first send this as a standalone PR. 

I add the embed etcd in Server field but do nothing, only for vendor. 

@ngaut @qiuyesuifeng @disksing @huachaohuang

### CODE REVIEW

**Comment by qiuyesuifeng** [comment]
LGTM
golang dependencies are really disaster :(

**Comment by ngaut** [comment]
Do we need to add it to tidb ?

**Comment by siddontang** [comment]
No, tidb don't need it.

**Comment by siddontang** [comment]
PTAL

**Comment by disksing** [comment]
LGTM

**Pull request merged**
