### PR TITLE
use dep instead glide

### PR DESCRIPTION
**Pull request by zhexuany**
This change is [Reviewable](https://reviewable.io/reviews/pingcap/pd/904)

### CODE REVIEW

**Comment by zhexuany** [comment]
@coocood @disksing @siddontang PTAL

**Comment by disksing** [comment]
Could you remove or update the _update_ section in _Makefile_?

**Comment by siddontang** [comment]
I think you must update `make update` and support `dep` update.

**Comment by zhexuany** [comment]
@disksing @siddontang sorry for the delay, I just updated update rule in `Makefile`

**Comment by disksing** [comment]
LGTM.

**Comment by disksing** [comment]
PTAL @Connor1996

**Pull request merged**
