### PR TITLE
*: use address instead of storeID for metrics

### LINKED ISSUE #1427: PD metrics should use TiKV instance, not store ID
Please answer these questions before submitting your issue. Thanks!

Now we have switched to use pull mode for TiKV and the Grafana for TiKV now uses instance instead of store ID. But for PD, it still uses store ID and it is hard for us to diagnose the problem for a TiKV between TiKV and PD metrics.  

image

### PR DESCRIPTION
**Pull request by rleungx**
### What problem does this PR solve? 
Closes #1427.

### What is changed and how it works?
This PR is going to use TiKV address instead of `storeID` for the metrics.

### Check List 

Tests 

 - Unit test

Related changes

 - Need to update the `tidb-ansible` repository

### CODE REVIEW

**Comment by disksing** [comment]
Why does it need to be cherry-picked to release branch?

**Comment by disksing** [comment]
Do we need to guide users to clean up old metrics data in release note? It may mess up if old and new format mix together.

**Comment by nolouch** [comment]
Do we need an API to find the `store id`?

**Comment by rleungx** [comment]
@disksing The current `release-2.1` branch of TiKV uses `instance`. I think we need to cherry-pick it to `release-2.1` branch of PD to keep consistent with TiKV. And for the label name, how about keeping using `store` rather than `address`?

**Comment by rleungx** [comment]
@nolouch Yes, it will be better. Maybe this work can be done by another PR?

**Comment by disksing** [comment]
> @disksing The current `release-2.1` branch of TiKV uses `instance`. I think we need to cherry-pick it to `release-2.1` branch of PD to keep consistent with TiKV. And for the label name, how about keeping using `store` rather than `address`?

I think use the same label name won't solve the problem I mentioned. Without clean up old data, there will be both label values of store id and store address.

**Comment by rleungx** [comment]
@disksing Oh, yes. But since we will change the label name and also change the expression of Grafana, the old data won't appear, right?

**Comment by disksing** [comment]
I don't think so. You may start a cluster to try it. @rleungx

**Comment by rleungx** [comment]
I have tested it and the old data won't appear.

**Comment by siddontang** [comment]
@rleungx 

seem now if you cherry pick to release, the user must upgrade the ansible too, right?

**Comment by rleungx** [comment]
@siddontang Yes. So do we need to cherry-pick it to release-2.1?

**Comment by siddontang** [comment]
@rleungx 

I think we don't need to merge to release.

**Comment by rleungx** [comment]
Ok.

**Pull request merged**
