### PR TITLE
[Cherry-pick] config: fix configs cannot set to zero values (#1334)

### PR DESCRIPTION
**Pull request by Connor1996**
### What problem does this PR solve? 
cherry pick #1334

### CODE REVIEW

**Comment by Connor1996** [comment]
/run-all-tests tidb=release-2.1 tikv=release-2.1 tidb-test=release-2.1

**Comment by nolouch** [comment]
/run-all-tests tidb=release-2.1 tikv=release-2.1 tidb-test=release-2.1

**Pull request merged**
