### PR TITLE
dashboard: attach html templates to pd binary

### PR DESCRIPTION
**Pull request by c4pt0r**

### CODE REVIEW

**Comment by c4pt0r** [comment]
Something wrong with CI? I checked the output log, may not cause by my PR.

**Comment by siddontang** [comment]
Do you merge the newest master before? 

@overvenus

**Comment by c4pt0r** [comment]
@overvenus any updates?

**Comment by siddontang** [comment]
Do you add this in glide.yml ?

**Comment by huachaohuang** [comment]
Should we add `bindata_assetfs.go` to git or should we generate it every build?

**Comment by c4pt0r** [comment]
@huachaohuang we won't create bindata_assetfs.go every time, only `make all` or `make build-fe` would re-generate the file.

**Comment by siddontang** [comment]
`make` will generate this file every time...

**Comment by c4pt0r** [comment]
@siddontang  I don't think so
...
default: build

all: dev build
...

**Comment by siddontang** [comment]
got it.

**Comment by huachaohuang** [comment]
I think templates are rarely changed, maybe we should `make build-fe` manually instead of adding it to `dev`?

**Comment by c4pt0r** [comment]
@huachaohuang Sounds good to me, I will change it in next commit.

**Comment by huachaohuang** [comment]
LGTM

**Comment by siddontang** [comment]
@c4pt0r 
Can we merge?

**Comment by c4pt0r** [comment]
Hold on, I found a bug, I'll fix it later.

**Pull request merged**
