### PR TITLE
schedule: add option to disable namespace checker

### PR DESCRIPTION
**Pull request by lerencao**
## What have you changed? (required)
This PR add an option to disable namespace checker's region relocation scheduling.

- disable-namespace-relocation

The implementation uses https://github.com/pingcap/pd/pull/1140 for reference.

## What are the type of the changes (required)?
- New feature (non-breaking change which adds functionality)

## How has this PR been tested (required)?
`make dev` and manual test.

## Does this PR affect documentation (docs/docs-cn) update? (optional)

TODO: add later

## Refer to a related PR or issue link (optional)
#1199

### CODE REVIEW

**Comment by disksing** [comment]
@lerencao Thanks for your contribution! If it is convenient, can you help me add the document? The related documents are located here: https://github.com/pingcap/docs/blob/master/tools/pd-control.md and https://github.com/pingcap/docs-cn/blob/master/tools/pd-control.md

**Comment by lerencao** [comment]
@disksing Yes, I'm doing it. :)

**Comment by lerencao** [comment]
PR on docs: https://github.com/pingcap/docs-cn/pull/840 and https://github.com/pingcap/docs/pull/573

**Pull request merged**
