### PR TITLE
[DNM] server: add region hot status

### PR DESCRIPTION
**Pull request by nolouch**
PTAL @siddontang @disksing

### CODE REVIEW

**Comment by disksing** [comment]
I think maintain 4 long-lived priority queues is a waste and hard to do it right. It would be much easier to only create a temporary heap to extract topN regions after receiving an API query.
What do you think? /cc @siddontang @zhangjinpeng1987

**Comment by siddontang** [comment]
@disksing 

If we have many regions, traveling all regions and get the topN may take a long time, we can do a test for it. 

Btw, I think we can only maintain a hot regions structure, maybe put the region to a LRU cache if the heartbeat contains any write or read, and then get the topN from the LRU cache. 

/cc @zhangjinpeng1987 @nolouch

**Comment by disksing** [comment]
Hi, I've written a simple test, https://gist.github.com/disksing/b0d184f491a02dbfe46616bac3d18131
output:
```
$ ./topn -r 10000 -n 100
1.53018ms

$ ./topn -r 50000 -n 100
7.753913ms

$ ./topn -r 100000 -n 100
17.33999ms
```

**Comment by nolouch** [comment]
@disksing  
I test  your code with modifying time start before extract r regions. if our region less 1000000 i think sort directly is also ok. there both are nlogn.
output:
```
 ./heap -r 1000000 -n 10
194.076603ms
./heap -r 5000000 -n 10
955.863451ms
./heap -r 10000000 -n 10 
3.322805835s
```

**Pull request closed without merging**
