### PR TITLE
travis: update go version

### PR DESCRIPTION
**Pull request by dvrkps**

### CODE REVIEW

**Comment by siddontang** [comment]
Seem we still need to support 1.8 @disksing

**Comment by dvrkps** [comment]
@disksing  @siddontang i add 1.8.x also

**Comment by ngaut** [comment]
Hi @dvrkps , go 1.9 is ok, could you please remove go 1.8.

**Comment by dvrkps** [comment]
@ngaut done.

**Comment by ngaut** [comment]
LGTM

**Pull request merged**
