### PR TITLE
*: update go version to 1.13

### PR DESCRIPTION
**Pull request by disksing**
### What problem does this PR solve? 
- After upgrading go to 1.13, `make dev` complains about `github.com/golang/protobuf/proto/testdata` not found.
- After `make ci`, theres is a unstaged `result.txt` file.

### What is changed and how it works?
- update go version to 1.13
- update golang_protobuf_extensions to reference a new version of protobuf
- update golang.org/x/{net, crypto, sync, sys} to latest
- ignore `result.txt` file for git

### Check List 

Tests 
 - No code

### CODE REVIEW

**Comment by disksing** [comment]
PTAL @nolouch @rleungx @Luffbee

**Comment by rleungx** [comment]
Does this PR need to cherry-pick to release-3.x branches?

**Comment by disksing** [comment]
We will manually update release branches after our CI environment is updated. @rleungx

**Pull request merged**
