### PR TITLE
client: check the timeout for creating stream

### PR DESCRIPTION
**Pull request by rleungx**
### What is changed and how it works?

This PR uses an extra goroutine to check if creating stream causes too much time and will call `cancel` once it reaches the timeout setting of the client.

### Check List

Tests

- TODO

### CODE REVIEW

**Comment by lhy1024** [comment]
LGTM

**Comment by disksing** [comment]
@rleungx Did you send PR to update TiDB dependency?

**Comment by rleungx** [comment]
> @rleungx Did you send PR to update TiDB dependency?

I will update it.

**Pull request merged**
