### PR TITLE
server: GetAllStores should not return tombstone stores (#1440)

### PR DESCRIPTION
**Pull request by nolouch**
### What problem does this PR solve? 
cherry pick #1440

### CODE REVIEW

**Comment by nolouch** [comment]
/run-all-tests tidb=release-2.1 tikv=release-2.1 tidb-test=release-2.1

**Comment by overvenus** [comment]
https://github.com/pingcap/kvproto/pull/361 has been merged, could you update kvproto?

**Comment by nolouch** [comment]
/run-all-tests tidb=release-2.1 tikv=release-2.1 tidb-test=release-2.1

**Comment by nolouch** [comment]
/run-all-tests tidb=release-2.1 tikv=release-2.1 tidb-test=release-2.1

**Comment by zhouqiang-cl** [comment]
/run-all-tests tidb=release-2.1 tikv=release-2.1 tidb-test=release-2.1

**Comment by zhouqiang-cl** [comment]
/run-all-tests tidb=release-2.1 tikv=release-2.1 tidb-test=release-2.1

**Comment by zhouqiang-cl** [comment]
/run-all-tests tidb=release-2.1 tikv=release-2.1 tidb-test=release-2.1

**Pull request merged**
