### PR TITLE
client: add timeout for rpc calls.

### PR DESCRIPTION
**Pull request by disksing**
To make pd client recover faster from network isolation.

### CODE REVIEW

**Comment by disksing** [comment]
Not able to reproduce the CI failure https://travis-ci.org/pingcap/pd/builds/267083024?utm_source=github_status&utm_medium=notification , add some logs.

**Comment by siddontang** [comment]
LGTM

**Comment by siddontang** [comment]
PTAL @tiancaiamao

**Comment by tiancaiamao** [comment]
LGTM

**Pull request merged**
