### PR TITLE
server: make the region heartbeat metric units correct

### PR DESCRIPTION
**Pull request by nolouch**
## What have you changed? (required)

In TiKV, we use seconds:

 
```rust
let now = SystemTime::now();
let ts = now.duration_since(UNIX_EPOCH).unwrap().as_secs();
req.set_timestamp(ts);
```
 

But in PD, we use milliseconds:

 ```go
regionHeartbeatLatency.WithLabelValues(storeLabel).Observe(float64(time.Now().UnixNano()/int64(time.Millisecond)) - float64(request.GetTimestamp()))
```

So the heartbeat latency is wrong now.let the unit correct.
## What are the type of the changes (required)?

- Bug fix (non-breaking change which fixes an issue)

## Refer to a related PR or issue link (optional)
https://github.com/pingcap/pd/issues/1121

### CODE REVIEW

**Comment by disksing** [comment]
Need to update the metric bucket too. Also the tidb-ansible grafana template need to update too.

**Comment by disksing** [comment]
LGTM. PTAL @Connor1996

**Comment by Connor1996** [comment]
Is unit of second enough to distinguish latency?

**Comment by nolouch** [comment]
@Connor1996  we only need to know if the heartbeat latency is increasing, that to judge handle the heartbeat become slower.

**Pull request merged**
