### PR TITLE
use user defined network

### LINKED ISSUE #65: run_cluster.sh doesn't form etcd cluster
run_cluster.sh doesn't form etcd cluster just because they can't connect to each other:

```
2016-04-06 12:55:08.363265 I | raft: 2a388ca50baf376d is starting a new election at term 7
2016-04-06 12:55:08.363301 I | raft: 2a388ca50baf376d became candidate at term 8
2016-04-06 12:55:08.363307 I | raft: 2a388ca50baf376d received vote from 2a388ca50baf376d at term 8
2016-04-06 12:55:08.363316 I | raft: 2a388ca50baf376d [logterm: 1, index: 3] sent vote request to 4246095a1fe1162a at term 8
2016-04-06 12:55:08.363323 I | raft: 2a388ca50baf376d [logterm: 1, index: 3] sent vote request to b305748795677bd4 at term 8
2016/04/06 12:55:08 grpc: Conn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:32379: getsockopt: connection refused"; Reconnecting to "127.0.0.1:32379"
2016-04-06 12:55:09.763264 I | raft: 2a388ca50baf376d is starting a new election at term 8
2016-04-06 12:55:09.763308 I | raft: 2a388ca50baf376d became candidate at term 9
2016-04-06 12:55:09.763318 I | raft: 2a388ca50baf376d received vote from 2a388ca50baf376d at term 9
2016-04-06 12:55:09.763326 I | raft: 2a388ca50baf376d [logterm: 1, index: 3] sent vote request to 4246095a1fe1162a at term 9
2016-04-06 12:55:09.763352 I | raft: 2a388ca50baf376d [logterm: 1, index: 3] sent vote request to b305748795677bd4 at term 9
2016/04/06 12:55:10 grpc: Conn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:32379: getsockopt: connection refused"; Reconnecting to "127.0.0.1:32379"
2016/04/06 12:55:10 main.go:38: [error] create pd server err grpc: timed out trying to connect

```
* pd: 2ec824a86a1efbbbc3cb182338e351378fd04be9
* Env: Docker 1.11-snapshot, Ubuntu 15.10

It seems that `docker run -p` is not working well with etcd.
Is is possible to use docker compose so as to eliminate `-p`? (excepts PD_ADVERTISE_ADDR)

### PR DESCRIPTION
**Pull request by siddontang**
Try to fix #65 

@ngaut @qiuyesuifeng

### CODE REVIEW

**Comment by siddontang** [comment]
@ AkihiroSuda

Can you use this to check again?

**Comment by AkihiroSuda** [comment]
@siddontang It seems working, thanks!

**Comment by ngaut** [comment]
LGTM. @AkihiroSuda Any suggestions ?

**Comment by qiuyesuifeng** [comment]
LGTM

**Comment by AkihiroSuda** [comment]
@ngaut LGTM

**Pull request merged**
