### PR TITLE
balance: avoid remove leader peer.

### PR DESCRIPTION
**Pull request by disksing**
Cherrypick of #671 on rc3. /cc @nolouch  @siddontang @overvenus

### CODE REVIEW

**Comment by siddontang** [comment]
CI failed

**Comment by disksing** [comment]
@siddontang It's caused by data race in grpc. I'll restart the test now and upgrade grpc/etcd later.

**Comment by siddontang** [comment]
LGTM

PTAL @huachaohuang

**Comment by huachaohuang** [comment]
LGTM

**Pull request merged**
