### PR TITLE
namespaceClassfier classifies region containing infinite edge

### PR DESCRIPTION
**Pull request by LiangShang**
Move the region to the corresponding namespace even if it contains infinite edge.

### CODE REVIEW

**Comment by siddontang** [comment]
Any test to cover the new condition check?

**Comment by LiangShang** [comment]
tests added in https://github.com/pingcap/pd/pull/789/files#diff-b64afae6ab3095b0229efacd2603633c

**Comment by siddontang** [comment]
LGTM

But we should not assume the region range is `[table ID, table ID + 1)` later. 

PTAL @disksing

**Comment by disksing** [comment]
LGTM.

**Pull request merged**
