### PR TITLE
Revert "dep: update packages."

### PR DESCRIPTION
**Pull request by zhexuany**
Reverts pingcap/pd#915

### Why should we revert this changes? 
We need merge this PR together with tidb. Otherwise, we ran into dependencies hell.

### CODE REVIEW

**Comment by zhexuany** [comment]
@disksing @coocood @tiancaiamao PTAL

**Comment by coocood** [comment]
LGTM

**Comment by tiancaiamao** [comment]
LGTM

**Comment by tiancaiamao** [comment]
LGTM

**Pull request merged**
