### PR TITLE
pdctl: fix some parameters of region not displaying

### PR DESCRIPTION
**Pull request by mantuliu**
### What problem does this PR solve? 
when I used the command 'pd-ctl region check empty-region'，output like this:

```
 {
      "id": 5404114,
      "start_key": "7480000000000002FFE500000000000000F8",
      "end_key": "7480000000000002FFE600000000000000F8",
      "epoch": {
        "conf_ver": 961,
        "version": 10348
      },
      "peers": [
        {
          "id": 5404116,
          "store_id": 1
        },
        {
          "id": 5770409,
          "store_id": 11
        },
        {
          "id": 5772468,
          "store_id": 8
        }
      ],
      "leader": {
        "id": 5404116,
        "store_id": 1
      },
      "approximate_size": 1
    }
```

I wanted to see the true value of approximate_keys,written_bytes,read_bytes ,because their true value is zero.

### What is changed and how it works?
remove the json 'omitempty' limit.

### Check List 

Tests 

 - Integration test

### CODE REVIEW

**Comment by disksing** [comment]
Why not update `WrittenKeys` and `ReadKeys` too?

**Comment by mantuliu** [comment]
@disksing 
At the beginning, I wanted to change these two parameters at the same time, but when I checked the output of our production environment, I found that the output of these two parameters was not found in our version 3.0.5. So I dare not modify these two values, because I didn't know the function of these two variables before. I will change these two values later, thank you!

**Comment by disksing** [comment]
@mantuliu Good to know. They are just like the other fields, only count by keys instead of sizes.

**Comment by disksing** [comment]
Thanks @mantuliu

**Pull request merged**
