### PR TITLE
server/api: remove unused static route

### PR DESCRIPTION
**Pull request by andelf**

### CODE REVIEW

**Comment by ngaut** [comment]
Good catch! LGTM.

**Comment by siddontang** [comment]
LGTM

**Comment by siddontang** [comment]
Do we need to remove event.go now?

**Comment by andelf** [comment]
```go
	router.Handle("/api/v1/events", newEventsHandler(svr, rd)).Methods("GET")
	router.Handle("/api/v1/feed", newFeedHandler(svr, rd)).Methods("GET")
```

**Comment by siddontang** [comment]
The event was used for the web shows, but seem useless now. 

/cc @disksing

**Comment by disksing** [comment]
We don't need web interface now?

**Comment by siddontang** [comment]
Maybe yes, we may supply another web interface, but not only in PD.  /cc @iamxy

**Comment by iamxy** [comment]
We will separate frontend resource from this repo.
LGTM

**Pull request merged**
