### PR TITLE
[DNM]Add embedded node exporter.

### PR DESCRIPTION
**Pull request by qiuyesuifeng**

### CODE REVIEW

**Comment by qiuyesuifeng** [comment]
@siddontang  @huachaohuang  @overvenus  PTAL
You can only review commit 55dc865.

**Comment by siddontang** [comment]
You can see the node exporter website that it supports extra collections for different platforms, we should at lease support linux.

**Comment by siddontang** [comment]
can we need to support a library so tidb can use it? or is it necessary for tidb to use node exportor?
@shenli

**Comment by siddontang** [comment]
LGTM

**Comment by overvenus** [comment]
LGTM

**Comment by siddontang** [comment]
should we close it now? @qiuyesuifeng

**Comment by qiuyesuifeng** [comment]
@siddontang OK.

**Pull request closed without merging**
