### PR TITLE
config: adjust default quota value to 8GB

### PR DESCRIPTION
**Pull request by nolouch**
Signed-off-by: nolouch <nolouch@gmail.com>

### What problem does this PR solve? 
Users may use multiple rules at once time, which case mvcc database no space.
enlarge the default quota value.

### What is changed and how it works?
add a default value.

### Check List 

Tests 

 - Unit test

### CODE REVIEW

**Comment by shafreeck** [comment]
I am wondering if it decreases the performance when setting to 8G.

**Comment by nolouch** [comment]
@shafreeck As https://github.com/etcd-io/etcd/blob/master/Documentation/faq.md#system-requirements, 8GB is a suggested maximum size for a normal environment, and we recommend using more than 8GB of memory for PD.  also I think the auto period compact can ensure performance.  How about your suggestion?

**Comment by nolouch** [comment]
@lhy1024  Actually officially recommend is 8GB. But I think the `compact` ensures that space less than 8GB, so no need to use swap in most cases.

**Comment by nolouch** [comment]
@lhy1024  Actually officially recommend is 8GB. But I think the `compact` ensures that space less than 8GB, so no need to use swap in most cases.

**Comment by siddontang** [comment]
do we have to plan to solve the too many multiple rules problem?

**Comment by nolouch** [comment]
@siddontang Yes, will do.

**Pull request merged**
