### PR TITLE
test: increase mustWaitLeader timeout.

### PR DESCRIPTION
**Pull request by huachaohuang**
Travis-CI can be very slow sometimes, etcd takes more than 10s to sync wal.

### CODE REVIEW

**Comment by qiuyesuifeng** [comment]
LGTM

**Comment by siddontang** [comment]
CI failed.

**Comment by siddontang** [comment]
Any update @huachaohuang

**Comment by huachaohuang** [comment]
@overvenus

**Comment by overvenus** [comment]
The failed test is `TestJoinSelfPDFailedAndRestarts`

The first PD starts with join itself and fails, it is restarted with the same configuration while other peers try to connect to it.

Since the original cluster ID is computed by the first PD, when the first PD restarts, with the same configuration, it will form a **new** cluster with the same cluster ID and the same peer ID.

If the restarted PD becomes leader of the new cluster before other peers reach it, we will have two leaders in two clusters, the leader of old cluster will send messages to the leader of the new cluster, the leader of new cluster accepts (because the old cluster has higher term) and becomes follower **temporary**, but soon it will become leader again. This happens again and again. **The test will fail when the new leader becomes follower.**

**Comment by siddontang** [comment]
@overvenus 
Why the join itself PD forms a new cluster? The data dir is cleaned up?

**Comment by overvenus** [comment]
Yes, the data dir is removed.

**Comment by siddontang** [comment]
so how to fix it?

**Comment by huachaohuang** [comment]
Seems we don't have any reasonable expected result in this test case, can we delete this test case?

**Comment by siddontang** [comment]
As @xiang90 said before, join is very dangerous, especially for join itself without data, we don't know the PD has been removed before or not. 
@iamxy do we really need join itself? If not, I prefer not supporting this or output a warning.

**Comment by overvenus** [comment]
I found another weird case:

Steps:
 1. Start pd1 (join self)
 2. Start pd2(join pd1)
 3. Start pd3(join pd2)
 4. Close pd1 and remove data
 5. Restart pd1, **works fine**
 6. Close pd1 and remove data
 7. Restart pd1, **panic**
 6. Close pd1 and remove data
 7. Restart pd1, **panic**
 8. Always panic...

Logs of pd1:
  - step 5:

    ```
2016/08/24 20:48:52 server.go:93: [info] PD config - Config({FlagSet:0xc820164cc0 ClientUrls:http://:12379 PeerUrls:http://:12380 AdvertiseClientUrls:http://:12379 AdvertisePeerUrls:http://:12380 Name:pd1 DataDir:default.pd1 InitialCluster:pd1=http://:12380 InitialClusterState:new Join:http://:12379 LeaderLease:3 LogLevel:info LogFile: TsoSaveInterval:2000 ClusterID:1 MaxPeerCount:3 BalanceCfg:{MinCapacityUsedRatio:0.3 MaxCapacityUsedRatio:0.9 MaxLeaderCount:10 MaxSendingSnapCount:3 MaxReceivingSnapCount:3 MaxDiffScoreFraction:0.1 BalanceInterval:30 MaxBalanceCount:16 MaxBalanceRetryPerLoop:10 MaxBalanceCountPerLoop:3 MaxTransferWaitCount:3 MaxPeerDownDuration:30m0s MaxStoreDownDuration:10m0s} nextRetryDelay:1000000000 configFile:})
2016/08/24 20:48:52 server.go:127: [info] start embed etcd 
2016-08-24 20:48:52.895467 I | embed: listening for peers on http://:12380
2016-08-24 20:48:52.895511 I | embed: listening for client requests on :12379
2016-08-24 20:48:52.933766 I | netutil: resolving :12380 to :12380
2016-08-24 20:48:52.933798 I | netutil: resolving :12380 to :12380
2016-08-24 20:48:52.933862 I | etcdserver: name = pd1
2016-08-24 20:48:52.933874 I | etcdserver: data dir = default.pd1
2016-08-24 20:48:52.933884 I | etcdserver: member dir = default.pd1/member
2016-08-24 20:48:52.933892 I | etcdserver: heartbeat = 100ms
2016-08-24 20:48:52.933899 I | etcdserver: election = 1000ms
2016-08-24 20:48:52.933908 I | etcdserver: snapshot count = 10000
2016-08-24 20:48:52.933931 I | etcdserver: advertise client URLs = http://:12379
2016-08-24 20:48:52.933947 I | etcdserver: initial advertise peer URLs = http://:12380
2016-08-24 20:48:52.933959 I | etcdserver: initial cluster = pd1=http://:12380
2016-08-24 20:48:52.980260 I | etcdserver: starting member f0fb8535be179b7d in cluster d17ba119828eeb7a
2016-08-24 20:48:52.980668 I | raft: f0fb8535be179b7d became follower at term 0
2016-08-24 20:48:52.980707 I | raft: newRaft f0fb8535be179b7d [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
2016-08-24 20:48:52.980724 I | raft: f0fb8535be179b7d became follower at term 1
2016-08-24 20:48:53.172179 I | etcdserver: starting server... [version: 3.0.0+git, cluster version: to_be_decided]
2016-08-24 20:48:53.172461 I | v2http: pprof is enabled under /debug/pprof
2016-08-24 20:48:53.172888 I | rafthttp: started HTTP pipelining with peer 19ed9c6eef13ff97
2016-08-24 20:48:53.172924 E | rafthttp: failed to find member 19ed9c6eef13ff97 in cluster d17ba119828eeb7a
2016-08-24 20:48:53.173010 I | raft: f0fb8535be179b7d [term: 1] received a MsgHeartbeat message with higher term from 19ed9c6eef13ff97 [term: 4]
2016-08-24 20:48:53.173043 I | raft: f0fb8535be179b7d became follower at term 4
2016-08-24 20:48:53.173117 I | raft: committed 1, tocommit 0
2016-08-24 20:48:53.173135 I | raft: raft.node: f0fb8535be179b7d elected leader 19ed9c6eef13ff97 at term 4
2016-08-24 20:48:53.173218 I | rafthttp: started HTTP pipelining with peer f43b47e168042122
2016-08-24 20:48:53.173251 E | rafthttp: failed to find member f43b47e168042122 in cluster d17ba119828eeb7a
2016-08-24 20:48:53.173275 I | membership: added member f0fb8535be179b7d [http://:12380] to cluster d17ba119828eeb7a
2016-08-24 20:48:53.173416 E | rafthttp: failed to find member f43b47e168042122 in cluster d17ba119828eeb7a
2016-08-24 20:48:53.173483 E | rafthttp: failed to find member 19ed9c6eef13ff97 in cluster d17ba119828eeb7a
2016-08-24 20:48:53.173566 I | raft: committed 1, tocommit 0
2016-08-24 20:48:53.173592 I | raft: committed 1, tocommit 0
2016-08-24 20:48:53.206316 I | rafthttp: peer 19ed9c6eef13ff97 became active
2016-08-24 20:48:53.219380 I | raft: committed 1, tocommit 249
2016-08-24 20:48:53.219411 I | raft: lastIndex 250, tocommit 249
2016-08-24 20:48:53.219707 N | membership: set the initial cluster version to 3.0
2016-08-24 20:48:53.219760 I | api: enabled capabilities for version 3.0
2016-08-24 20:48:53.219986 I | membership: added member 19ed9c6eef13ff97 [http://:32380] to cluster d17ba119828eeb7a
2016-08-24 20:48:53.220014 I | rafthttp: starting peer 19ed9c6eef13ff97...
2016-08-24 20:48:53.220051 I | rafthttp: started HTTP pipelining with peer 19ed9c6eef13ff97
2016-08-24 20:48:53.222819 I | rafthttp: started streaming with peer 19ed9c6eef13ff97 (writer)
2016-08-24 20:48:53.224758 I | rafthttp: started peer 19ed9c6eef13ff97
2016-08-24 20:48:53.224821 I | rafthttp: added peer 19ed9c6eef13ff97
2016-08-24 20:48:53.225473 I | membership: added member f43b47e168042122 [http://:22380] to cluster d17ba119828eeb7a
2016-08-24 20:48:53.225527 I | rafthttp: starting peer f43b47e168042122...
2016-08-24 20:48:53.225573 I | rafthttp: started HTTP pipelining with peer f43b47e168042122
2016-08-24 20:48:53.225699 I | rafthttp: started streaming with peer 19ed9c6eef13ff97 (writer)
2016-08-24 20:48:53.225799 I | rafthttp: started streaming with peer 19ed9c6eef13ff97 (stream MsgApp v2 reader)
2016-08-24 20:48:53.225884 I | rafthttp: started streaming with peer 19ed9c6eef13ff97 (stream Message reader)
2016-08-24 20:48:53.229039 I | rafthttp: started streaming with peer f43b47e168042122 (writer)
2016-08-24 20:48:53.234784 I | rafthttp: started streaming with peer f43b47e168042122 (writer)
2016-08-24 20:48:53.235690 I | rafthttp: peer 19ed9c6eef13ff97 became active
2016-08-24 20:48:53.235738 I | rafthttp: established a TCP streaming connection with peer 19ed9c6eef13ff97 (stream Message reader)
2016-08-24 20:48:53.236792 I | rafthttp: started peer f43b47e168042122
2016-08-24 20:48:53.236837 I | rafthttp: added peer f43b47e168042122
2016-08-24 20:48:53.237536 I | rafthttp: started streaming with peer f43b47e168042122 (stream MsgApp v2 reader)
2016-08-24 20:48:53.238239 I | rafthttp: established a TCP streaming connection with peer 19ed9c6eef13ff97 (stream MsgApp v2 reader)
2016-08-24 20:48:53.238989 I | rafthttp: started streaming with peer f43b47e168042122 (stream Message reader)
2016-08-24 20:48:53.239712 I | rafthttp: peer f43b47e168042122 became active
2016-08-24 20:48:53.239754 I | rafthttp: established a TCP streaming connection with peer f43b47e168042122 (stream Message reader)
2016-08-24 20:48:53.239867 I | rafthttp: established a TCP streaming connection with peer f43b47e168042122 (stream MsgApp v2 reader)
2016-08-24 20:48:53.257237 I | raft: committed 249, tocommit 0
2016-08-24 20:48:53.269756 I | raft: committed 249, tocommit 250
2016-08-24 20:48:53.269814 I | raft: lastIndex 250, tocommit 250
2016-08-24 20:48:53.270194 I | etcdserver: published {Name:pd1 ClientURLs:[http://:12379]} to cluster d17ba119828eeb7a
```

  - after step 5:

    ```
2016/08/24 20:50:34 server.go:93: [info] PD config - Config({FlagSet:0xc82015d0e0 ClientUrls:http://:12379 PeerUrls:http://:12380 AdvertiseClientUrls:http://:12379 AdvertisePeerUrls:http://:12380 Name:pd1 DataDir:default.pd1 InitialCluster:pd1=http://:12380 InitialClusterState:new Join:http://:12379 LeaderLease:3 LogLevel:info LogFile: TsoSaveInterval:2000 ClusterID:1 MaxPeerCount:3 BalanceCfg:{MinCapacityUsedRatio:0.3 MaxCapacityUsedRatio:0.9 MaxLeaderCount:10 MaxSendingSnapCount:3 MaxReceivingSnapCount:3 MaxDiffScoreFraction:0.1 BalanceInterval:30 MaxBalanceCount:16 MaxBalanceRetryPerLoop:10 MaxBalanceCountPerLoop:3 MaxTransferWaitCount:3 MaxPeerDownDuration:30m0s MaxStoreDownDuration:10m0s} nextRetryDelay:1000000000 configFile:})
2016/08/24 20:50:34 server.go:127: [info] start embed etcd 
2016-08-24 20:50:34.485849 I | embed: listening for peers on http://:12380
2016-08-24 20:50:34.485885 I | embed: listening for client requests on :12379
2016-08-24 20:50:34.527331 I | netutil: resolving :12380 to :12380
2016-08-24 20:50:34.527395 I | netutil: resolving :12380 to :12380
2016-08-24 20:50:34.527487 I | etcdserver: name = pd1
2016-08-24 20:50:34.527504 I | etcdserver: data dir = default.pd1
2016-08-24 20:50:34.527515 I | etcdserver: member dir = default.pd1/member
2016-08-24 20:50:34.527525 I | etcdserver: heartbeat = 100ms
2016-08-24 20:50:34.527534 I | etcdserver: election = 1000ms
2016-08-24 20:50:34.527551 I | etcdserver: snapshot count = 10000
2016-08-24 20:50:34.527564 I | etcdserver: advertise client URLs = http://:12379
2016-08-24 20:50:34.527576 I | etcdserver: initial advertise peer URLs = http://:12380
2016-08-24 20:50:34.527590 I | etcdserver: initial cluster = pd1=http://:12380
2016-08-24 20:50:34.600076 I | etcdserver: starting member f0fb8535be179b7d in cluster d17ba119828eeb7a
2016-08-24 20:50:34.600158 I | raft: f0fb8535be179b7d became follower at term 0
2016-08-24 20:50:34.600186 I | raft: newRaft f0fb8535be179b7d [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
2016-08-24 20:50:34.600206 I | raft: f0fb8535be179b7d became follower at term 1
2016-08-24 20:50:34.760308 I | etcdserver: starting server... [version: 3.0.0+git, cluster version: to_be_decided]
2016-08-24 20:50:34.760890 I | v2http: pprof is enabled under /debug/pprof
2016-08-24 20:50:34.762848 I | membership: added member f0fb8535be179b7d [http://:12380] to cluster d17ba119828eeb7a
2016-08-24 20:50:34.762998 I | rafthttp: started HTTP pipelining with peer f43b47e168042122
2016-08-24 20:50:34.763047 E | rafthttp: failed to find member f43b47e168042122 in cluster d17ba119828eeb7a
2016-08-24 20:50:34.763516 I | raft: f0fb8535be179b7d [term: 1] received a MsgHeartbeat message with higher term from 19ed9c6eef13ff97 [term: 4]
2016-08-24 20:50:34.763603 I | raft: f0fb8535be179b7d became follower at term 4
2016-08-24 20:50:34.763830 I | raft: committed 1, tocommit 255
2016-08-24 20:50:34.763868 I | raft: lastIndex 1, tocommit 255
2016-08-24 20:50:34.763913 C | raft: tocommit(255) is out of range [lastIndex(1)]. Was the raft log corrupted, truncated, or lost?
2016-08-24 20:50:34.764074 I | rafthttp: started HTTP pipelining with peer 19ed9c6eef13ff97
2016-08-24 20:50:34.764166 E | rafthttp: failed to find member 19ed9c6eef13ff97 in cluster d17ba119828eeb7a
panic: tocommit(255) is out of range [lastIndex(1)]. Was the raft log corrupted, truncated, or lost?
goroutine 40 [running]:
panic(0xe50000, 0xc8201bbb50)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/pingcap/pd/vendor/github.com/coreos/pkg/capnslog.(*PackageLogger).Panicf(0xc82013ba40, 0x1493860, 0x5d, 0xc8201b9200, 0x2, 0x2)
	/home/neil/repo/gopath/src/github.com/pingcap/pd/vendor/github.com/coreos/pkg/capnslog/pkg_logger.go:75 +0x191
github.com/pingcap/pd/vendor/github.com/coreos/etcd/raft.(*raftLog).commitTo(0xc82000a230, 0xff)
	/home/neil/repo/gopath/src/github.com/pingcap/pd/vendor/github.com/coreos/etcd/raft/log.go:191 +0x466
```

**Panic**: [github.com/coreos/etcd/raft/log.go:191](https://github.com/coreos/etcd/blob/master/raft/log.go#L187)

I logged etcd internal commit information:

```go
func (l *raftLog) commitTo(tocommit uint64) {
	// never decrease commit
	l.logger.Infof("committed %v, tocommit %v", l.committed, tocommit)
	if l.committed < tocommit {
		l.logger.Infof("lastIndex %v, tocommit %v", l.lastIndex(), tocommit)
		if l.lastIndex() < tocommit {
			l.logger.Panicf("tocommit(%d) is out of range [lastIndex(%d)]. Was the raft log corrupted, truncated, or lost?", tocommit, l.lastIndex())
		}
		l.committed = tocommit
	}
}
```

outputs:

```
2016-08-24 20:48:53.219380 I | raft: committed 1, tocommit 249
2016-08-24 20:48:53.219411 I | raft: lastIndex 250, tocommit 249
```

It really confuses me, why etcd log jumps and **only** jumps at step 5 ?

**Comment by siddontang** [comment]
so I think we would better not supporting join itself.

**Comment by qiuyesuifeng** [comment]
Agreed.

**Comment by overvenus** [comment]
Agreed, but the problem is still here, I think we should warn users that do not start a cluster with one PD, and recommend at least three.

**Comment by siddontang** [comment]
we can log a warning if starting one PD.
But at same time, we will don't allow join only itself, the `join` must be used with joining current cluster.

**Comment by siddontang** [comment]
LGTM

**Comment by siddontang** [comment]
@overvenus fire another issue to fix join problem.

**Pull request merged**
