### PR TITLE
server: fix the race condition of region heartbeats from different regions

### PR DESCRIPTION
**Pull request by youjiali1995**
Signed-off-by: youjiali1995 <zlwgx1023@gmail.com>

### What problem does this PR solve? 
Fix https://github.com/pingcap/pd/issues/2149

### What is changed and how it works?
Check the validation of the region heartbeat again before putting it.

### Check List 

Tests 
 - No code

Code changes

Side effects

Related changes

 - Need to cherry-pick to the release branch

### CODE REVIEW

**Comment by rleungx** [comment]
Can we add a test to cover this case?

**Comment by youjiali1995** [comment]
> Can we add a test to cover this case?

Yes.

**Comment by youjiali1995** [comment]
@nolouch @rleungx PTAL, thanks!

**Comment by rleungx** [comment]
@youjiali1995 Please resolve the conflict.

**Comment by youjiali1995** [comment]
> @youjiali1995 Please resolve the conflict.

Sorry for the late reply. PTAL again. @rleungx

**Pull request merged**
