### PR TITLE
server: merge status_address/git_hash fields of store meta

### PR DESCRIPTION
**Pull request by lonng**
Signed-off-by: Lonng <heng@lonng.org>

### What problem does this PR solve? 

The TiKV uses `status_address` to provide HTTP service for external components. But the original store metadata does not contain the `status_address` and `git_hash` information, so the TiDB cannot get the `status_address` from PD via `GetAllStores` gRPC interface. Furthermore, TiDB cannot use the HTTP service provided by TiKV.

This PR adds the support that reports the status_address and git_hash to PD on TiKV startup to make subsequent work easier.

Related change: 
- https://github.com/pingcap/kvproto/pull/481
- https://github.com/tikv/tikv/pull/5760

### CODE REVIEW

**Comment by lonng** [comment]
@nolouch Hi, please approve https://github.com/tikv/tikv/pull/5760 too.

**Comment by disksing** [comment]
What is git hash used for?

**Comment by lonng** [comment]
@disksing `select * from information_schema.tidb_cluster_info` should display the  git_hash of every component.

**Pull request merged**
