### PR TITLE
test: improve coverage for rule.go 

### PR DESCRIPTION
**Pull request by Yisaer**
### What problem does this PR solve?

improve the coverage for `rule.go` by covering the error handling.

ref https://github.com/pingcap/pd/issues/2287

Related changes

- Need to cherry-pick to the release branch

### CODE REVIEW

**Comment by Yisaer** [comment]
@sunzhuohang PTAL

**Comment by sunzhuohang** [comment]
LGTM

**Comment by disksing** [comment]
Great work! @Yisaer

**Pull request merged**
