### PR TITLE
*: update etcd to v3.2.2 and fix a stream related issue.

### PR DESCRIPTION
**Pull request by disksing**
About the issue:
because the streams are long-term existence in our usage scenario, stream will not be shut down if the server loses leadership and no new message is received on the stream. Here `Recv` with timeout is introduced to solve this problem.

cc @nolouch @siddontang

### CODE REVIEW

**Comment by nolouch** [comment]
LGTM. 
Btw, I see etcd also fix graceful close problem in 3.2.4. maybe we can update to it.

**Comment by siddontang** [comment]
seem this should be two PR, one for the vendor, one for the stream?

**Comment by disksing** [comment]
@nolouch @siddontang I'll try 3.2.4, seems we don't need to use the timeout Recv anymore.

**Comment by disksing** [comment]
See #686

**Pull request closed without merging**
