### PR TITLE
fix data race.

### PR DESCRIPTION
**Pull request by huachaohuang**

### CODE REVIEW

**Comment by qiuyesuifeng** [comment]
Could you show more details where has the race problem?

**Comment by huachaohuang** [comment]
See this log https://s3.amazonaws.com/archive.travis-ci.org/jobs/158374705/log.txt
`leaderConn` may be accessed by two goroutines, the one running the connection may write to `leaderConn`, the another closing the connection may read `leaderConn`.
So I create a `leaderProxy` which only lives inside `run()`, no other goroutines may access it.

**Comment by qiuyesuifeng** [comment]
LGTM

**Comment by overvenus** [comment]
LGTM

**Pull request merged**
