### PR TITLE
server/leader: use the compact revision to watch leader (#1396)

### PR DESCRIPTION
**Pull request by nolouch**
* server/leader: use the compact revision to watch leader

### What problem does this PR solve? 
Cherry pick #1396  to 2.1 branch.

### CODE REVIEW

**Comment by nolouch** [comment]
/run-all-tests tidb=release-2.1 tikv=release-2.1 tidb-test=release-2.1

**Comment by huachaohuang** [comment]
Tests failed.

**Comment by zhouqiang-cl** [comment]
/run-all-tests tidb=release-2.1 tikv=release-2.1 tidb-test=release-2.1

**Comment by zhouqiang-cl** [comment]
/run-all-tests tidb=release-2.1 tikv=release-2.1 tidb-test=release-2.1

**Comment by zhouqiang-cl** [comment]
/run-all-tests tidb=release-2.1 tikv=release-2.1 tidb-test=release-2.1

**Comment by zhouqiang-cl** [comment]
/run-all-tests tidb=release-2.1 tikv=release-2.1 tidb-test=release-2.1

**Comment by zhouqiang-cl** [comment]
/run-all-tests tidb=release-2.1 tikv=release-2.1 tidb-test=release-2.1

**Comment by zhouqiang-cl** [comment]
/run-all-tests tidb=release-2.1 tikv=release-2.1 tidb-test=release-2.1

**Comment by zhouqiang-cl** [comment]
/run-all-tests tidb=release-2.1 tikv=release-2.1 tidb-test=release-2.1

**Comment by zhouqiang-cl** [comment]
/run-all-tests tidb=release-2.1 tikv=release-2.1 tidb-test=release-2.1

**Comment by zhouqiang-cl** [comment]
/run-all-tests tidb=release-2.1 tikv=release-2.1 tidb-test=release-2.1

**Comment by zhouqiang-cl** [comment]
/run-all-tests tidb=release-2.1 tikv=release-2.1 tidb-test=release-2.1

**Comment by zhouqiang-cl** [comment]
/run-all-tests tidb=release-2.1 tikv=release-2.1 tidb-test=release-2.1

**Comment by zhouqiang-cl** [comment]
/run-all-tests tidb=release-2.1 tikv=release-2.1 tidb-test=release-2.1

**Comment by zhouqiang-cl** [comment]
I have migrate the old jenkins to new jenkins. we need to keep both run for a week. Now I am dig into why old jenkins failed

**Comment by zhouqiang-cl** [comment]
/run-all-tests tidb=release-2.1 tikv=release-2.1 tidb-test=pr/714

**Pull request merged**
