### PR TITLE
vendor: update the package of etcd

### PR DESCRIPTION
**Pull request by zimulala**
I need to use the function of `Leader`.

### CODE REVIEW

**Comment by zimulala** [comment]
PTAL @disksing @coocood

**Comment by disksing** [comment]
@zimulala CI failed. Seems we have to switch to go1.8

**Comment by coocood** [comment]
@zimulala 
The `github/pingcap/check` is removed from vendor.

@disksing 
tranvis is alread 1.8.

**Comment by siddontang** [comment]
CI failed @zimulala

**Comment by zimulala** [comment]
@coocood Yep. Because `github/pingcap/check` is used in test. I import this package now. 
@disksing  said may be randomly generated port number is too big lead, let me wait for a PR ,@siddontang

**Comment by zimulala** [comment]
The version of `8bad78cb98739eed7bbf1f94b218a7fa5dc5611a` have some problem about when the service is closed. So I change the version.

**Comment by siddontang** [comment]
LGTM

**Comment by nolouch** [comment]
LGTM

**Pull request merged**
